### ISSUE TITLE
Error Conrete 8.0.2

### ISSUE THREAD

**Issue by tigerxy** [dszymczuk/dsEventCalendar57#2]
Installed the newest version of Concrete5 and the addon stopped working.
`Call to a member function generate() on null`

**Comment by dszymczuk** [comment]
I've not tested C5 8 yet.

**Comment by dszymczuk** [comment]
http://www.concrete5.org/community/forums/usage/concrete-5.8-page-in-dashboard-call-to-a-member-function-generat/#860087

**Comment by dszymczuk** [comment]
http://www.concrete5.org/community/forums/usage/concrete-5.8-page-in-dashboard-call-to-a-member-function-generat/
