### ISSUE TITLE
Update Package to 8.5.0

### ISSUE THREAD

**Issue by xdubx** [dszymczuk/dsEventCalendar57#5]
Hello guys,

do you still work at this project and can upate it to the current version?

**Comment by dszymczuk** [comment]
@xdubx Hi, unfortunately, I dropped the project year ago.

**Comment by tigerxy** [comment]
@xdubx Concrete5 has now a builtin calendar. It's better integrated than this addon. Do you miss a feature? Why do you want to use this addon?

**Comment by xdubx** [comment]
Currently you can not sync a ics file. You don't have the option to set the height. 

I have now programmly overwrite the current block with my custom version. 
Better integrated? Ok in my option for backend resons, but edit visual stuff and functionaly you are limited to the basics.
More than the half of functions are not used from the js lib from fullcalender.io.
Unfortunately I use version 8.3 and don't take a look to the new 8.5 version calender. But the patch notes says nothing new for the calender features.

**Comment by tigerxy** [comment]
@xdubx Yes you are right, iCal is not supported from the official c5 calendar.
Long time ago I developed the iCal export function for this addon. When you are interested in, I can try to integrate this part in the official c5 calendar.

**Comment by xdubx** [comment]
I needed a importer (solved it by adding the passed ical into the view by the block). But if you have code in a repository that work. It would perhaps be interesting for other users if the function exists. :)

**Comment by tigerxy** [comment]
@xdubx what do you mean with importer? Do you want to import ics file to c5 or export from c5 to ics?
